name: game_of_qr
description: A new Flutter project.

publish_to: "none"
version: 1.0.1+2
platforms:
  ios:
  android:

environment:
  sdk: ">=2.17.5 <3.2.0"

dependencies:
  austerity: ^1.1.0
  camera: ^0.10.5+5
  collection:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  google_mlkit_barcode_scanning: ^0.10.0
  path_provider: ^2.1.1
  qr: ^3.0.1
  super_tooltip: ^2.0.7

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/java.png
    - assets/marble.png
    - assets/wood.png
