name: game_of_qr
description: A new Flutter project.

publish_to: 'none'
version: 1.0.1+2
platforms:
  ? ios
  ? android

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  camera: ^0.10.0+3
  collection: ^1.16.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  google_mlkit_barcode_scanning: ^0.5.0
  path_provider: ^2.0.14
  qr: ^3.0.1
  super_tooltip: ^1.0.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/java.png
    - assets/marble.png
    - assets/wood.png
